services:
  - type: web
    name: cv-analyzer
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: NLTK_DATA
        value: "/opt/render/project/src/nltk_data"
      - key: ADMIN_TOKEN
        generateValue: true
